name: Sort and Concatenate Files

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sort and Concatenate
        run: |
          # Sort all files in charts folder and merges into merged file
          cd charts
          for f in *; do

            #changes tabs to space in filename (better for pixel watch's small display)
            sed -i 's/\t/ /g' "$f";
            
            #remove unnecessary chars from filename
            echo "$f:" | sed 's/_/ /g' | sed 's/.tsv//g' | cat;

            #print the file contents and two newlines
            cat "$f";
            printf "\n\n";
            
          done > ../all-charts.txt

          cat ../all-charts.txt

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: merged-file
          path: all-charts.txt
