name: Sort and Concatenate Files

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Sort and Concatenate
        run: |
          # Sort all files in charts folder and merges into merged file
          cd charts
          for f in *; do
            
            #remove unnecessary chars from filename
            echo "$f:" | sed 's/_/ /g' | sed 's/.tsv//g' | cat;

            #print the file contents with space
            cat "$f";
            printf "\n";
            
          done > ../all-charts-tabs.txt

          cd ..

          cat all-charts-tabs.txt

          #changes tabs to space in filename (better for pixel watch's small display)
          sed 's/\t/ /g' "all-charts-tabs.txt" > "all-charts-spaces.txt";

          python "code/compress-txt.py"

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: merged-file
          path: |
            all-charts-tabs.txt
            all-charts-spaces.txt
