name: Sort and Concatenate Files

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sort and Concatenate
        run: |
          # Sort all files in charts folder and merges into merged file
          cd charts
          for f in *;
            sed -i 's/\t/ \t/g' "$f"
            do printf "%s:\n" "$f";
            cat "$f";
            printf "\n";
            done > ../all-charts.tsv

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: merged-file
          path: all-charts.tsv
